config/routes.rb
Rails.application.routes.draw do
  resources :breadcrumbs
  resource :users, except: %i[new]
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  post "/", to: "breadcrumbs#create"
  root "breadcrumbs#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breadcrumb.rb
class Breadcrumb < ApplicationRecord
  belongs_to :breadcrumb_master
  belongs_to :user
  # enum content_status: [:close, :open, :draft, :garbage]
end

app/models/breadcrumb_category.rb
class BreadcrumbCategory < ApplicationRecord
  has_many :breadcrumb_masters_categories, dependent: :nullify
  has_many :breadcrumb_masters, through: :breadcrumb_masters_categories
end

app/models/breadcrumb_master.rb
class BreadcrumbMaster < ApplicationRecord
  has_many :breadcrumbs, dependent: :nullify
  has_many :breadcrumb_masters_categories, dependent: :nullify
  has_many :breadcrumb_categories, through: :breadcrumb_masters_categories
end

app/models/breadcrumb_masters_category.rb
class BreadcrumbMastersCategory < ApplicationRecord
  belongs_to :breadcrumb_master
  belongs_to :breadcrumb_category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :breadcrumbs, dependent: :delete_all
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
  include SessionsHelper
end

app/controllers/breadcrumbs_controller.rb
class BreadcrumbsController < ApplicationController
  def new
    # 入力項目のマスタデータの初期値取得
    @breadcrumb_masters = BreadcrumbMaster.includes(:breadcrumb_categories).where(breadcrumb_categories: { id: 1 })
    @breadcrumbs = if signed_in?
                     current_user.breadcrumbs.build
                   else
                     # ゲストユーザー
                     User.first.breadcrumbs.build
                   end
  end

  def create
    @breadcrumbs = if signed_in?
                     current_user.breadcrumbs.build(create_breadcrumbs_params)
                   else
                     # ゲストユーザー
                     User.first.breadcrumbs.build(create_breadcrumbs_params)
                   end

    breadcrumbs = @breadcrumbs.map do |breadcrumb|
      # insert_allは時間を補完しない Enumを適用してくれないため
      breadcrumb["content_status"] = 0
      breadcrumb["created_at"] = Time.zone.now
      breadcrumb["updated_at"] = Time.zone.now
      breadcrumb.attributes
    end

    Breadcrumb.insert_all breadcrumbs
    redirect_to root_path
  end

  private

  def create_breadcrumbs_params
    params.permit(breadcrumbs: %i[content breadcrumb_master_id]).require(:breadcrumbs)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      sign_in user
      flash[:notice] = "サインインしました"
      redirect_to root_path
    else
      flash.now[:danger] = "サインインに失敗しました"
      render "sessions/new"
    end
  end

  def destroy
    signed_out
    flash[:notice] = "サインアウトしました"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(create_user_params)
    if @user.save
      redirect_to signin_path
    else
      render "users/new"
    end
  end

  private

  def create_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      title: "Face UP",
      description: "お店やブログや企業サイトなどを運営しているSEO担当者向けにJSON-LD構造化データを自動抽出します。",
      keywords: "JSON-LD, SEO, 構造化, パンくず, マークアップ"
    }
  end
end

app/helpers/breadcrumbs_helper.rb
module BreadcrumbsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # サインイン時に取得したuser_idをsessionに入れる
  def sign_in(user)
    session[:user_id] = user.id
  end

  # 現在のログインユーザーを取得
  def current_user
    User.find_by(id: session[:user_id])
  end

  # ログイン中の場合trueを返す
  def signed_in?
    !current_user.nil?
  end

  def signed_out
    session.delete(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/breadcrumbs/new.html.slim
h1 Json-LD構造化抽出フォーム
= form_for @breadcrumbs, url: "/" do |f|
  = render partial: "template/validation_error", locals: { errors: @breadcrumbs.errors }
  - @breadcrumb_masters.each do |breadcrumb_master|
    = fields_for "breadcrumbs[]" do |ff|
      = ff.hidden_field :breadcrumb_master_id, value: breadcrumb_master.id
      = ff.label :content, breadcrumb_master.content
      = ff.text_field :content
  = f.submit 'Jsonを出力する'

app/views/layouts/application.html.slim
doctype html
html lang == 'ja'
  head
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    = display_meta_tags default_meta_tags

  body
    header class='header'
      = link_to 'サインアップ', signup_path
      = link_to 'サインイン', signin_path
      = link_to 'サインアウト', signout_path, method: :delete
    - flash.each do |key, val|
      div class="notification-#{key}"
        = val
    = yield

app/views/template/_validation_error.html.slim
- if errors.any?
  - errors.full_messages.each do |msg|
    p.c-alert = msg

app/views/users/new.html.slim
h1 Users#new
p Find me in app/views/users/new.html.slim
= form_for @user, url: "/signup" do |f|
  = render partial: "template/validation_error", locals: { errors: @user.errors }
  = f.label :name, 'ユーザー名'
  = f.text_field :name, placeholder: '30文字以内で入力してください'
  = f.label :email, 'メールアドレス'
  = f.email_field :email, placeholder: '必須入力'
  = f.label :password, 'パスワード'
  = f.password_field :password, placeholder: '72文字以内で入力してください'
  = f.label :password_confirmation, 'パスワード確認用'
  = f.password_field :password_confirmation, placeholder: '72文字以内で入力してください'
  = f.submit 'ユーザー登録'